In [4]:
# AI-Based Recruitment Screening Lab

## Lab Objective
The objective of this lab is to help learners understand how an AI-assisted recruitment system works at a basic level.

## Learning Outcome
- Understand recruitment data
- Apply TF-IDF & cosine similarity
- Rank candidates using AI-assisted scoring

SyntaxError: invalid syntax (3090581231.py, line 4)

In [3]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("Libraries imported successfully.")

Libraries imported successfully.

In [5]:
## Step 1: Create Dataset

In [6]:
data = [
    {"candidate_id": 1, "name": "Aarav", "skills": "python sql machine learning excel", "experience_years": 3, "education": "B.Tech", "certifications": 2},
    {"candidate_id": 2, "name": "Diya", "skills": "excel communication recruitment onboarding", "experience_years": 4, "education": "MBA HR", "certifications": 1},
    {"candidate_id": 3, "name": "Kabir", "skills": "python pandas data analysis sql tableau", "experience_years": 2, "education": "B.Sc", "certifications": 3},
    {"candidate_id": 4, "name": "Ishita", "skills": "java sql spring communication teamwork", "experience_years": 5, "education": "B.Tech", "certifications": 2},
    {"candidate_id": 5, "name": "Vivaan", "skills": "python sql deep learning nlp bert", "experience_years": 6, "education": "M.Tech", "certifications": 4},
    {"candidate_id": 6, "name": "Anaya", "skills": "recruitment sourcing interview screening communication", "experience_years": 3, "education": "MBA HR", "certifications": 2},
    {"candidate_id": 7, "name": "Reyansh", "skills": "python sql power bi excel statistics", "experience_years": 4, "education": "B.Tech", "certifications": 2},
    {"candidate_id": 8, "name": "Myra", "skills": "machine learning python data visualization tableau", "experience_years": 2, "education": "M.Sc", "certifications": 3},
    {"candidate_id": 9, "name": "Arjun", "skills": "manual testing selenium jira communication", "experience_years": 5, "education": "BCA", "certifications": 1},
    {"candidate_id": 10, "name": "Siya", "skills": "python sql ml nlp communication teamwork", "experience_years": 3, "education": "MCA", "certifications": 3},
    {"candidate_id": 11, "name": "Krish", "skills": "excel sql reporting dashboard power bi", "experience_years": 2, "education": "B.Com", "certifications": 2},
    {"candidate_id": 12, "name": "Aadhya", "skills": "python r statistics machine learning", "experience_years": 4, "education": "M.Stat", "certifications": 3},
    {"candidate_id": 13, "name": "Advik", "skills": "project management agile scrum communication", "experience_years": 6, "education": "MBA", "certifications": 2},
    {"candidate_id": 14, "name": "Kiara", "skills": "python sql data analysis recruitment hr analytics", "experience_years": 5, "education": "MBA HR", "certifications": 4},
    {"candidate_id": 15, "name": "Atharv", "skills": "c++ algorithms data structures problem solving", "experience_years": 1, "education": "B.Tech", "certifications": 1},
    {"candidate_id": 16, "name": "Navya", "skills": "python sql tableau power bi communication", "experience_years": 3, "education": "BBA", "certifications": 2},
    {"candidate_id": 17, "name": "Rudra", "skills": "nlp bert transformers python machine learning", "experience_years": 5, "education": "M.Tech", "certifications": 4},
    {"candidate_id": 18, "name": "Sara", "skills": "recruitment analytics excel communication hr operations", "experience_years": 4, "education": "MBA HR", "certifications": 2},
    {"candidate_id": 19, "name": "Vihaan", "skills": "python sql statistics data cleaning pandas", "experience_years": 2, "education": "B.Sc", "certifications": 2},
    {"candidate_id": 20, "name": "Meera", "skills": "python machine learning sql communication dashboards", "experience_years": 4, "education": "MCA", "certifications": 3}
]

df = pd.DataFrame(data)

print("Dataset created")
df.head()

Dataset created

   candidate_id    name                                      skills  experience_years education  certifications
0             1   Aarav           python sql machine learning excel                 3    B.Tech               2
1             2    Diya  excel communication recruitment onboarding                 4    MBA HR               1
2             3   Kabir     python pandas data analysis sql tableau                 2      B.Sc               3
3             4  Ishita      java sql spring communication teamwork                 5    B.Tech               2
4             5  Vivaan           python sql deep learning nlp bert                 6    M.Tech               4

In [7]:
print("Shape:", df.shape)
print("Columns:", df.columns)

Shape: (20, 6)
Columns: Index(['candidate_id', 'name', 'skills', 'experience_years', 'education', 'certifications'], dtype='object')

In [8]:
df.head()

   candidate_id    name                                      skills  experience_years education  certifications
0             1   Aarav           python sql machine learning excel                 3    B.Tech               2
1             2    Diya  excel communication recruitment onboarding                 4    MBA HR               1
2             3   Kabir     python pandas data analysis sql tableau                 2      B.Sc               3
3             4  Ishita      java sql spring communication teamwork                 5    B.Tech               2
4             5  Vivaan           python sql deep learning nlp bert                 6    M.Tech               4

In [9]:
job_description = "python sql machine learning nlp communication dashboards recruitment analytics"

print(job_description)

python sql machine learning nlp communication dashboards recruitment analytics

In [10]:
documents = [job_description] + df["skills"].tolist()

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

print(tfidf_matrix.shape)

(21, 46)

In [11]:
job_vector = tfidf_matrix[0:1]
candidate_vectors = tfidf_matrix[1:]

similarity_scores = cosine_similarity(job_vector, candidate_vectors).flatten()

df["similarity_score"] = similarity_scores

In [12]:
df["experience_score"] = df["experience_years"] / df["experience_years"].max()
df["certification_score"] = df["certifications"] / df["certifications"].max()

In [13]:
education_map = {
    "B.Com": 0.50,
    "BBA": 0.55,
    "BCA": 0.55,
    "B.Sc": 0.60,
    "B.Tech": 0.70,
    "MBA": 0.75,
    "MBA HR": 0.80,
    "MCA": 0.80,
    "M.Sc": 0.80,
    "M.Tech": 0.90,
    "M.Stat": 0.90
}

df["education_score"] = df["education"].map(education_map).fillna(0.5)

In [14]:
df["final_score"] = (
    0.50 * df["similarity_score"] +
    0.25 * df["experience_score"] +
    0.15 * df["education_score"] +
    0.10 * df["certification_score"]
)

In [15]:
ranked_df = df.sort_values(by="final_score", ascending=False).reset_index(drop=True)

ranked_df["rank"] = ranked_df.index + 1

ranked_df.head()

   candidate_id    name                                             skills  experience_years education  certifications  similarity_score  experience_score  certification_score  education_score  final_score  rank
0            20   Meera  python machine learning sql communication dash...                 4       MCA               3          0.755230          0.666667                 0.75              0.8     0.739282     1
1             5  Vivaan                  python sql deep learning nlp bert                 6    M.Tech               4          0.373774          1.000000                 1.00              0.9     0.671887     2
2            17   Rudra      nlp bert transformers python machine learning                 5    M.Tech               4          0.418469          0.833333                 1.00              0.9     0.652568     3
3            14   Kiara  python sql data analysis recruitment hr analytics                 5    MBA HR               4          0.406514          0.833333                 1.00              0.8     0.631590     4
4            12  Aadhya               python r statistics machine learning                 4    M.Stat               3          0.382899          0.666667                 0.75              0.9     0.568116     5

In [16]:
top_5 = ranked_df.head(5)

top_5

   candidate_id    name                                             skills  experience_years education  certifications  similarity_score  experience_score  certification_score  education_score  final_score  rank
0            20   Meera  python machine learning sql communication dash...                 4       MCA               3          0.755230          0.666667                 0.75              0.8     0.739282     1
1             5  Vivaan                  python sql deep learning nlp bert                 6    M.Tech               4          0.373774          1.000000                 1.00              0.9     0.671887     2
2            17   Rudra      nlp bert transformers python machine learning                 5    M.Tech               4          0.418469          0.833333                 1.00              0.9     0.652568     3
3            14   Kiara  python sql data analysis recruitment hr analytics                 5    MBA HR               4          0.406514          0.833333                 1.00              0.8     0.631590     4
4            12  Aadhya               python r statistics machine learning                 4    M.Stat               3          0.382899          0.666667                 0.75              0.9     0.568116     5

In [17]:
def label_candidate(score):
    if score >= 0.65:
        return "Strong Match"
    elif score >= 0.50:
        return "Moderate Match"
    else:
        return "Low Match"

ranked_df["recommendation"] = ranked_df["final_score"].apply(label_candidate)

In [18]:
final_output = ranked_df[[
    "candidate_id",
    "name",
    "skills",
    "experience_years",
    "education",
    "certifications",
    "similarity_score",
    "experience_score",
    "education_score",
    "certification_score",
    "final_score",
    "recommendation"
]]

final_output

    candidate_id     name                                             skills  experience_years education  certifications  similarity_score  experience_score  education_score  certification_score  final_score  recommendation
0             20    Meera  python machine learning sql communication dash...                 4       MCA               3          0.755230          0.666667             0.80                 0.75     0.739282    Strong Match
1              5   Vivaan                  python sql deep learning nlp bert                 6    M.Tech               4          0.373774          1.000000             0.90                 1.00     0.671887    Strong Match
2             17    Rudra      nlp bert transformers python machine learning                 5    M.Tech               4          0.418469          0.833333             0.90                 1.00     0.652568    Strong Match
3             14    Kiara  python sql data analysis recruitment hr analytics                 5    MBA HR               4          0.406514          0.833333             0.80                 1.00     0.631590  Moderate Match
4             12   Aadhya               python r statistics machine learning                 4    M.Stat               3          0.382899          0.666667             0.90                 0.75     0.568116  Moderate Match
5             18     Sara  recruitment analytics excel communication hr o...                 4    MBA HR               2          0.364453          0.666667             0.80                 0.50     0.518893  Moderate Match
6              1    Aarav                  python sql machine learning excel                 3    B.Tech               2          0.461985          0.500000             0.70                 0.50     0.510992  Moderate Match
7             10     Siya           python sql ml nlp communication teamwork                 3       MCA               3          0.349575          0.500000             0.80                 0.75     0.494788       Low Match
8             13    Advik       project management agile scrum communication                 6       MBA               2          0.061943          1.000000             0.75                 0.50     0.443472       Low Match
9              2     Diya         excel communication recruitment onboarding                 4    MBA HR               1          0.246840          0.666667             0.80                 0.25     0.435087       Low Match
10             4   Ishita             java sql spring communication teamwork                 5    B.Tech               2          0.128840          0.833333             0.70                 0.50     0.427753       Low Match
11             8     Myra  machine learning python data visualization tab...                 2      M.Sc               3          0.275516          0.333333             0.80                 0.75     0.416091       Low Match
12             6    Anaya  recruitment sourcing interview screening commu...                 3    MBA HR               2          0.188620          0.500000             0.80                 0.50     0.389310       Low Match
13             7  Reyansh               python sql power bi excel statistics                 4    B.Tech               2          0.119317          0.666667             0.70                 0.50     0.381325       Low Match
14            16    Navya          python sql tableau power bi communication                 3       BBA               2          0.204367          0.500000             0.55                 0.50     0.359683       Low Match
15             9    Arjun         manual testing selenium jira communication                 5       BCA               1          0.061943          0.833333             0.55                 0.25     0.346805       Low Match
16             3    Kabir            python pandas data analysis sql tableau                 2      B.Sc               3          0.113584          0.333333             0.60                 0.75     0.305125       Low Match
17            19   Vihaan         python sql statistics data cleaning pandas                 2      B.Sc               2          0.109594          0.333333             0.60                 0.50     0.278130       Low Match
18            11    Krish             excel sql reporting dashboard power bi                 2     B.Com               2          0.052342          0.333333             0.50                 0.50     0.234504       Low Match
19            15   Atharv     c++ algorithms data structures problem solving                 1    B.Tech               1          0.000000          0.166667             0.70                 0.25     0.171667       Low Match

In [19]:
final_output.to_csv("recruitment_screening_output.csv", index=False)

from google.colab import files
files.download("recruitment_screening_output.csv")